# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170516_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=None, max_length=500, verbose_name='内容'),
        ),
    ]
